### ISSUE TITLE
Testing before a release

### ISSUE THREAD

**Issue by 907th** [907th/mina-clockwork#2]
@estepan I merged your PR and added some fixes. Do you have an ability to test the latest version of this gem on a real project/server? I just want to be sure that all is correct before releasing to rubygems.

**Comment by estepan** [comment]
@907th I'm already using `master` branch on one of my projects staging server. Everything is smooth. However, I'd suggest adding a notice to the README about explicitly setting up `bundle_bin`. Because in `launch` block when you are using `rbenv` it cannot find bundle in `PATH`. I had trouble with that.

**Comment by 907th** [comment]
@estepan How did you resolved it? I think that rbenv users should `require 'mina/rbenv'` and `invoke :'rbenv:load'`, it should make `bundle` command available without having to override `:bundle_bin` option manually.

**Comment by estepan** [comment]
That's the first approach.
But it forces you to invoke `rbenv:load` on each step of deployment.
I installed `bundler` via `gem install` so it appears in `~/.rbenv/shims`. Then I assigned `:bundle_bin` to `~/.rbenv/shims/bundle`

**Comment by 907th** [comment]
@estepan Typically you should `invoke :'rbenv:load'` in an `:environment` task which is executed only once before every other task (at the start of the deploy, not on each step).

**Comment by 907th** [comment]
@estepan I also added a fallback to `clockworkd` (without `bundle exec` prefix) when no `:bundle_bin` set in 4a29d42

**Comment by 907th** [comment]
@estepan 🎉  I've released `v1.0.0`. Thank you for your help!
